In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets as datasets
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split

data = pd.read_csv(
    'log01HEBING3foldnafillmedian3.csv',
)

print(len(data))
data.head()

target = data[['PRE']]
features = data.drop('PRE', axis=1) 
features = features.drop(['Tail.Length','Wing.Length', 'pop.decreasing', 'pop.stable', 'pop.increasing','mig_strictmig','mig_partialmigrant','mig_resident'], axis=1)

# features = features.drop('pop.trend', axis=1) 
# features = features.drop('mig.type', axis=1)
features.head()


X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.2,random_state=0)
# X_train.shape
# X_train.ndim
X_test.shape
# print(X_test)


311


(63, 22)

In [2]:
#Convert a two-dimensional array to a one-dimensional array
flattened_X_train = X_train.values
flattened_y_train = y_train.values.ravel().astype(np.int64)
flattened_X_test = X_test.values
flattened_y_test = y_train.values.ravel().astype(np.int64)

flattened_X_train[np.isnan(flattened_X_train)] = 2
flattened_X_test[np.isnan(flattened_X_test)] = 2

In [3]:
print(flattened_y_train)

[1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 1
 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 1 1
 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0
 1 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 0
 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1
 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0]


In [3]:
X_num_train = flattened_X_train[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].astype(np.float32)
X_bin_train = flattened_X_train[:, [19]].astype(np.float32)
X_cat_train = flattened_X_train[:, [0,20,21]].astype(np.int32)

X_num_test = flattened_X_test[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].astype(np.float32)
X_bin_test = flattened_X_test[:, [19]].astype(np.float32)
X_cat_test = flattened_X_test[:, [0,20,21]].astype(np.int32)

#print(X_cat_train.dtype)
# print(X_cat_test)
X_num_test.shape

(63, 18)

In [10]:
np.save('./tabular-dl-tabr/data/my_dataset/X_num_train.npy', X_num_train) 
np.save('./tabular-dl-tabr/data/my_dataset/X_bin_train.npy', X_bin_train)
np.save('./tabular-dl-tabr/data/my_dataset/X_cat_train.npy', X_cat_train)

np.save('./tabular-dl-tabr/data/my_dataset/X_num_val.npy', X_num_test)
np.save('./tabular-dl-tabr/data/my_dataset/X_bin_val.npy', X_bin_test)
np.save('./tabular-dl-tabr/data/my_dataset/X_cat_val.npy', X_cat_test)

np.save('./tabular-dl-tabr/data/my_dataset/X_num_test.npy', X_num_test)
np.save('./tabular-dl-tabr/data/my_dataset/X_bin_test.npy', X_bin_test)
np.save('./tabular-dl-tabr/data/my_dataset/X_cat_test.npy', X_cat_test)

#label
np.save('./tabular-dl-tabr/data/my_dataset/Y_train.npy', flattened_y_train)
np.save('./tabular-dl-tabr/data/my_dataset/Y_val.npy', flattened_y_test)


In [8]:
# data =np.load('./tabular-dl-tabr/data/classif-cat-medium-0-rl/X_cat_train.npy')
# print(data.dtype)
# # print(arr.dtype)
# data.shape
da= np.load('./tabular-dl-tabr/data/my_dataset/X_cat_train.npy')
print(da.dtype)
da= np.load('./tabular-dl-tabr/data/classif-cat-medium-0-rl/X_cat_train.npy')
print(da)
# da.shape
# data1 =np.load('./tabular-dl-tabr/data/classif-cat-medium-0-rl/X_bin_test.npy')
# print(data1)
# da1= np.load('./tabular-dl-tabr/data/my_dataset/X_bin_test.npy')
# print(da1)
# data2 =np.load('./tabular-dl-tabr/data/classif-cat-medium-0-rl/X_cat_test.npy')
# print(data2)
# da2= np.load('./tabular-dl-tabr/data/my_dataset/X_cat_val.npy')
# print(da2)

<U32
[[ 2  2  1 19]
 [ 2  2  2 19]
 [ 2  0  1 19]
 ...
 [ 2  0  2 19]
 [ 2  0  2 19]
 [ 2  0  2 19]]


In [5]:
#只保留5行num_train 试一试   
#5行train，2行val，3行test
X_num_train_5 = X_num_train[:11]
print(X_num_train_5)
X_num_val_2 = X_num_test[:2]
print(X_num_val_2)
X_num_test_3 = X_num_test[:3]
print(X_num_test_3)


# X_num_test_3.shape
np.save('./tab-ddpm/data/test/X_num_train.npy', X_num_train_5) 
np.save('./tab-ddpm/data/test/X_num_val.npy', X_num_val_2) 
np.save('./tab-ddpm/data/test/X_num_test.npy', X_num_test_3) 

y_train_5 = flattened_y_train[:11]
print(y_train_5)
y_val_2 = flattened_y_test[:2]
print(y_val_2)
np.save('./tab-ddpm/data/test/y_train.npy', y_train_5) 
np.save('./tab-ddpm/data/test/y_val.npy',y_val_2) 
y_test_3 = flattened_y_test[:3]
print(y_test_3)
np.save('./tab-ddpm/data/test/y_test.npy',y_test_3) 

[[  0.4    0.     0.     0.     0.     0.6    0.     0.8    0.1    0.1
    0.     1.62   1.85   7.07  42.23   3.14   1.41   1.27]
 [  0.6    0.     0.     0.1    0.1    0.1    0.1    0.1    0.4    0.1
    0.4    0.98   1.91   7.3   45.71   0.     1.23   0.93]
 [  1.     0.     0.     0.     0.     0.     0.     0.     0.5    0.5
    0.     1.02   1.52   6.71  -2.35   0.     1.22   1.21]
 [  1.     0.     0.     0.     0.     0.     0.     0.     0.8    0.2
    0.     1.33   1.71   6.14  -8.2    0.     1.3    1.31]
 [  0.8    0.2    0.     0.     0.     0.     0.     0.4    0.4    0.2
    0.     1.52   1.88   6.3   -9.49   0.     1.49   1.32]
 [  1.     0.     0.     0.     0.     0.     0.     0.5    0.5    0.
    0.     1.25   1.85   6.77  -3.8    0.     1.31   1.2 ]
 [  0.9    0.     0.     0.     0.     0.1    0.     0.25   0.25   0.25
    0.25   0.93   1.94   6.2  -28.73   0.     1.27   1.11]
 [  0.     0.     0.     0.     0.     1.     0.     0.4    0.3    0.3
    0.     1.43   1

In [24]:
 
#用head删除下面的行试试 train 248 val 63 test2
X_num_train_5 = X_num_train[:248]
print(X_num_train_5)
X_num_val_2 = X_num_test[:63]
print(X_num_val_2)
X_num_test_3 = X_num_test[:3]
print(X_num_test_3)


# X_num_test_3.shape
np.save('./tab-ddpm/data/malaria/X_num_train.npy', X_num_train_5) 
np.save('./tab-ddpm/data/malaria/X_num_val.npy', X_num_val_2) 
np.save('./tab-ddpm/data/malaria/X_num_test.npy', X_num_test_3) 

y_train_5 = flattened_y_train[:248]
print(y_train_5)
y_val_2 = flattened_y_test[:63]
print(y_val_2)
np.save('./tab-ddpm/data/malaria/y_train.npy', y_train_5) 
np.save('./tab-ddpm/data/malaria/y_val.npy',y_val_2) 
y_test_3 = flattened_y_test[:3]
print(y_test_3)
np.save('./tab-ddpm/data/malaria/y_test.npy',y_test_3) 

[[0.4  0.   0.   ... 3.14 1.41 1.27]
 [0.6  0.   0.   ... 0.   1.23 0.93]
 [1.   0.   0.   ... 0.   1.22 1.21]
 ...
 [0.3  0.   0.   ... 3.18 1.3  1.16]
 [0.3  0.   0.   ... 0.   1.25 1.15]
 [0.5  0.   0.   ... 0.   1.32 1.17]]
[[0.5  0.   0.   ... 2.9  1.28 1.1 ]
 [0.6  0.   0.   ... 0.   1.42 1.34]
 [0.2  0.   0.   ... 0.   1.45 1.31]
 ...
 [0.3  0.   0.   ... 0.   1.3  1.21]
 [0.2  0.   0.   ... 0.   1.24 1.13]
 [0.4  0.   0.   ... 0.   1.37 1.18]]
[[ 0.5   0.    0.    0.    0.    0.5   0.    1.    0.    0.    0.    1.16
   1.82  6.39 33.63  2.9   1.28  1.1 ]
 [ 0.6   0.    0.    0.3   0.1   0.    0.    0.2   0.4   0.2   0.2   1.69
   1.95  6.98 -1.63  0.    1.42  1.34]
 [ 0.2   0.    0.    0.3   0.    0.5   0.    1.    0.    0.    0.    2.13
   1.89  7.12 -3.84  0.    1.45  1.31]]
[1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 1
 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1

In [34]:

X_cat_train = flattened_X_train[:248, [0,20,21]].astype(str)
X_cat_val = flattened_X_test[:63, [0,20,21]].astype(str)
X_cat_test = X_cat_val[:3]

np.save('./tab-ddpm/data/malaria/X_cat_train.npy', X_cat_train)
np.save('./tab-ddpm/data/malaria/X_cat_val.npy', X_cat_val)
np.save('./tab-ddpm/data/malaria/X_cat_test.npy', X_cat_test)


In [10]:
 
#用head删除下面的行试试 train 248 val 63 test2
X_num_train_5 = X_num_train[:248]
print(X_num_train_5)
X_num_val_2 = X_num_test[:63]
print(X_num_val_2)
X_num_test_3 = X_num_test[:3]
print(X_num_test_3)


# X_num_test_3.shape
np.save('./tabular-dl-tabr/data/malaria/X_num_train.npy', X_num_train_5) 
np.save('./tabular-dl-tabr/data/malaria/X_num_val.npy', X_num_val_2) 
np.save('./tabular-dl-tabr/data/malaria/X_num_test.npy', X_num_test_3) 

X_cat_train = flattened_X_train[:248, [0,20,21]].astype(np.str_)
X_cat_val = flattened_X_test[:63, [0,20,21]].astype(np.str_)
X_cat_test = X_cat_val[:3]

np.save('./tabular-dl-tabr/data/malaria/X_cat_train.npy', X_cat_train)
np.save('./tabular-dl-tabr/data/malaria/X_cat_val.npy', X_cat_val)
np.save('./tabular-dl-tabr/data/malaria/X_cat_test.npy', X_cat_test)

y_train_5 = flattened_y_train[:248].astype(np.int64)
print(y_train_5)
y_val_2 = flattened_y_test[:63].astype(np.int64)
print(y_val_2)
np.save('./tabular-dl-tabr/data/malaria/Y_train.npy', y_train_5) 
np.save('./tabular-dl-tabr/data/malaria/Y_val.npy',y_val_2) 
y_test_3 = flattened_y_test[:3].astype(np.int64)
print(y_test_3)
np.save('./tabular-dl-tabr/data/malaria/Y_test.npy',y_test_3) 

[[0.4  0.   0.   ... 3.14 1.41 1.27]
 [0.6  0.   0.   ... 0.   1.23 0.93]
 [1.   0.   0.   ... 0.   1.22 1.21]
 ...
 [0.3  0.   0.   ... 3.18 1.3  1.16]
 [0.3  0.   0.   ... 0.   1.25 1.15]
 [0.5  0.   0.   ... 0.   1.32 1.17]]
[[0.5  0.   0.   ... 2.9  1.28 1.1 ]
 [0.6  0.   0.   ... 0.   1.42 1.34]
 [0.2  0.   0.   ... 0.   1.45 1.31]
 ...
 [0.3  0.   0.   ... 0.   1.3  1.21]
 [0.2  0.   0.   ... 0.   1.24 1.13]
 [0.4  0.   0.   ... 0.   1.37 1.18]]
[[ 0.5   0.    0.    0.    0.    0.5   0.    1.    0.    0.    0.    1.16
   1.82  6.39 33.63  2.9   1.28  1.1 ]
 [ 0.6   0.    0.    0.3   0.1   0.    0.    0.2   0.4   0.2   0.2   1.69
   1.95  6.98 -1.63  0.    1.42  1.34]
 [ 0.2   0.    0.    0.3   0.    0.5   0.    1.    0.    0.    0.    2.13
   1.89  7.12 -3.84  0.    1.45  1.31]]
[1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 1
 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1